name: CI/CD Pipeline

on:
  push:
    branches:
      - desarrollo
  pull_request:
    branches:
      - desarrollo

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: juansesues
        password: Juanse59264

    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./Backend
        push: true
        tags: your-dockerhub-username/bookingapp-backend:latest

  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: juansesues
        password: Juanse59264

    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./Frontend
        push: true
        tags: your-dockerhub-username/bookingapp-frontend:latest